name: Build and Push Docker Image to GHCR

# Run this workflow on push to the main branch and on pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (to support advanced build features)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Backend image
      - name: Build and Push Backend image
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: ghcr.io/kxn2004/quickbite/backend:latest

      # Build and push the Frontend image
      - name: Build and Push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          tags: ghcr.io/kxn2004/quickbite/frontend:latest

      # Optionally, you can cache Docker layers to speed up subsequent builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
